/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n7JnfqMuFaV
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Label } from "@/components/ui/label";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { SVGProps } from "react";

export function Landing() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <VoteIcon className="h-6 w-6" />
          <span className="sr-only">D&lsquo;Hondt Voting System</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            How it Works
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="https://discord.gg/spstwqN6aH"
            target="_blank"
          >
            Community
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="https://github.com/voto-desperdicado"
          >
            Contribute
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48" id="hero">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Understanding the D&lsquo;Hondt Voting System in Portugal
                  </h1>
                  <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                    The D&lsquo;Hondt voting system is used in Portugal to
                    allocate parliamentary seats based on population. Learn how
                    this system works and how it impacts regional
                    representation.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Learn More
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                    href="https://discord.gg/spstwqN6aH"
                    target="_blank"
                  >
                    Join the Community
                  </Link>
                </div>
              </div>
              <img
                alt="D&lsquo;Hondt Voting System"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
                height="550"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32"
          id="party-selection"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Select Your Party
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Understand Your Vote&lsquo;s Impact
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Select the party you vote for to see how your vote contributes
                  to the distribution of seats in the Portuguese parliament.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-2">
                  <Label htmlFor="party">Select Your Party</Label>
                  <Select>
                    <SelectTrigger id="party">
                      <SelectValue placeholder="Select a party" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="party-a">Party A</SelectItem>
                      <SelectItem value="party-b">Party B</SelectItem>
                      <SelectItem value="party-c">Party C</SelectItem>
                      <SelectItem value="party-d">Party D</SelectItem>
                      <SelectItem value="party-e">Party E</SelectItem>
                      <SelectItem value="party-f">Party F</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">
                    Your Party&lsquo;s Representation in Parliament
                  </h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Based on the D&lsquo;Hondt system, your party received X% of
                    the total votes, resulting in Y parliamentary seats.
                  </p>
                </div>
              </div>
              <img
                alt="D&lsquo;Hondt Voting System Visualization"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32"
          id="region-selection"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Select Your Region
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Understand Your Vote&lsquo;s Power
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Select the region where you vote to see how your vote
                  contributes to the representation in the Portuguese
                  parliament.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-2">
                  <Label htmlFor="region">Select Your Region</Label>
                  <Select>
                    <SelectTrigger id="region">
                      <SelectValue placeholder="Select a region" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="lisbon">Lisbon</SelectItem>
                      <SelectItem value="porto">Porto</SelectItem>
                      <SelectItem value="algarve">Algarve</SelectItem>
                      <SelectItem value="alentejo">Alentejo</SelectItem>
                      <SelectItem value="centro">Centro</SelectItem>
                      <SelectItem value="norte">Norte</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">
                    Your Vote&lsquo;s Impact in Parliament
                  </h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Based on the D&lsquo;Hondt system, your region has X
                    parliamentary seats, representing Y% of the total.
                  </p>
                </div>
              </div>
              <img
                alt="D&lsquo;Hondt Voting System Visualization"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="how-it-works">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  D&lsquo;Hondt Voting System
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  How the System Works
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  The D&lsquo;Hondt voting system is used in Portugal to
                  allocate parliamentary seats based on population. This means
                  that different regions have varying levels of representation
                  in the national parliament.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                alt="D&lsquo;Hondt Voting System Visualization"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">
                    Proportional Representation
                  </h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    The D&lsquo;Hondt system ensures that the distribution of
                    parliamentary seats is proportional to the population of
                    each region.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">
                    Varying Representation Levels
                  </h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Due to population differences, some regions have more
                    parliamentary seats than others, leading to varying levels
                    of representation.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">
                    Inclusive Decision-Making
                  </h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    The D&lsquo;Hondt system aims to ensure that all regions
                    have a voice in the national parliament, promoting inclusive
                    decision-making.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
          id="community"
        >
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Join the D&lsquo;Hondt Voting System Community
              </h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Connect with others interested in understanding and improving
                the D&lsquo;Hondt voting system in Portugal.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row lg:justify-end">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="https://discord.gg/spstwqN6aH"
                target="_blank"
              >
                Join Discord
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="https://github.com/voto-desperdicado"
                target="_blank"
              >
                Contribute on GitHub
              </Link>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 border-t"
          id="contribute"
        >
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Help Improve the D&lsquo;Hondt Voting System
              </h2>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function VoteIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 12 2 2 4-4" />
      <path d="M5 7c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v12H5V7Z" />
      <path d="M22 19H2" />
    </svg>
  );
}
